version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./app.py:/server/app.py
      - archive:/server/archive
      - secret:/server/secret
    ports:
      - "5001:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./my-app:/app
    ports:
      - "7255:7255"
    depends_on:
      - backend

volumes:
  archive:
  secret:
